version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB='django'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='1111'
      - POSTGRES_HOST=db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME='django'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='1111'
      - POSTGRES_HOST=db
    depends_on:
      - db
