# Generated by Django 4.0.5 on 2022-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=0)),
                ('sum', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
